remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Baptiste CONTRERAS - blog]
description: ["IT blog, talking about PHP, cyber security and devops"]